[package]
name = "madsim-aws-sdk-s3"
version = "0.2.6"
edition = "2021"
authors = ["Kevin Axel <kevinaxel@163.com>"]
description = "The s3 simulator on madsim."
homepage = "https://github.com/madsim-rs/madsim"
repository = "https://github.com/madsim-rs/madsim"
categories = ["network-programming", "asynchronous", "simulation"]
keywords = ["s3", "api", "client", "async", "simulator"]
readme = "README.md"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(madsim))'.dependencies]
aws-sdk-s3 = "0.19"

[target.'cfg(madsim)'.dependencies]
madsim = { version = "0.2.9" }
# aws-types = "0.49.0"
aws-types = { package = "madsim-aws-types", path = "../madsim-aws-types" }
aws-smithy-http = "0.49.0"
aws-smithy-types = "0.49.0"
bytes = "1.2.1"
http = '0.2'
spin = "0.9"
tracing = "0.1"
tonic = { version = "0.8", default-features = false }

